# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NoiseRaster
                                 A QGIS plugin
 This plugin processes noise rasters
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-09-06
        copyright            : (C) 2021 by wetransform gmbh
        email                : kl@wetransform.to
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load NoiseRaster class from file NoiseRaster.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .noise_raster import NoiseRaster
    return NoiseRaster(iface)
